# Generated by Django 3.1.7 on 2021-03-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210306_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='date_creat',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='date_update',
            field=models.DateTimeField(),
        ),
    ]
