# Generated by Django 3.1.7 on 2021-03-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210306_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='date_creat',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='date_update',
            field=models.DateField(),
        ),
    ]
