# Generated by Django 3.1.7 on 2021-03-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210306_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='date_creat',
            field=models.DateField(),
        ),
    ]
