# Generated by Django 3.1.7 on 2021-03-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20210306_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='status',
            field=models.CharField(choices=[('active', 'Разное'), ('blocked', 'Заблокировано')], default='active', max_length=100),
        ),
    ]
