# Generated by Django 3.1.7 on 2021-03-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_guest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=100),
        ),
    ]
